### ISSUE TITLE
build-step failure

### ISSUE THREAD

**Issue by arcgang** [openshift/pipelines-tutorial#15] opened 2019-08-05 00:07 UTC
When triggering the pipeline, I am encountering the following issue:

> [build : build-step-git-source-petclinic-git-4wq7q] {"level":"warn","ts":1564963582.9377377,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
> [build : build-step-git-source-petclinic-git-4wq7q] {"level":"info","ts":1564963583.5528753,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/spring-projects/spring-petclinic @ master in path /workspace/source"}
> 
> [build : build-step-generate] Application dockerfile generated in /gen-source/Dockerfile.gen
> 
> [build : build-step-image-digest-exporter-generate-l2bw2] []
> 
> [build : build-step-build] STEP 1: FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
> [build : build-step-build] Getting image source signatures
> [build : build-step-build] Copying blob sha256:5c2598df456066d90ae3ed81592c54247800071c7ee8845985a93db7e95e936f
> [build : build-step-build] Copying blob sha256:dc4e07da33bca48edefbcba8dadefa8e7ffc6fe3e8ee4db140600a62862a16ac
> [build : build-step-build] Copying blob sha256:50408d34b7db1a7cac449215c8bf82b020a4e61bd542f66a8766b4804f3882fe
> [build : build-step-build] Copying config sha256:b1a978b29b74ee26fe1adf1c95a533cf56c815b87f9a742fac28ce493f9fc894
> [build : build-step-build] Writing manifest to image destination
> [build : build-step-build] Storing signatures
> [build : build-step-build] STEP 2: LABEL "io.openshift.s2i.build.image"="registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift"       "io.openshift.s2i.build.source-location"="."
> [build : build-step-build] 8b2b389b626d89517df954c54d3715dce9d066c482e1580e85ce2c7938d25017
> [build : build-step-build] STEP 3: USER root
> [build : build-step-build] 4f804bba78e994166483a49012491687e9be8cd785085ac152105dcf86bd2278
> [build : build-step-build] STEP 4: COPY upload/src /tmp/src
> [build : build-step-build] error building at STEP "COPY upload/src /tmp/src": no files found matching "/workspace/upload/src": no such file or directory
> 
> failed to get logs for task build : container build-step-build has failed  : Error

**Comment by siamaksade** [comment] 2019-08-08 10:24
@arcgang could you share your pipeline yaml? I can't reproduce this. Runs successfully when I try it

**Comment by raffamendes** [comment] 2019-09-30 15:52
Running into the same issue, using the tutorial pipeline
``
Name:         petclinic-deploy-pipeline
Namespace:    pipelines-tutorial
Labels:       <none>
Annotations:  <none>
API Version:  tekton.dev/v1alpha1
Kind:         Pipeline
Metadata:
  Creation Timestamp:  2019-09-30T14:35:05Z
  Generation:          1
  Resource Version:    235517
  Self Link:           /apis/tekton.dev/v1alpha1/namespaces/pipelines-tutorial/pipelines/petclinic-deploy-pipeline
  UID:                 7eb56f64-e38f-11e9-833d-52fdfc072182
Spec:
  Resources:
    Name:  app-git
    Type:  git
    Name:  app-image
    Type:  image
  Tasks:
    Name:  build
    Params:
      Name:   TLSVERIFY
      Value:  false
    Resources:
      Inputs:
        Name:      source
        Resource:  app-git
      Outputs:
        Name:      image
        Resource:  app-image
    Task Ref:
      Name:  s2i-java-8
    Name:    deploy
    Params:
      Name:   ARGS
      Value:  rollout latest spring-petclinic
    Run After:
      build
    Task Ref:
      Name:  openshift-client
Events:      <none>

**Comment by raffamendes** [comment] 2019-09-30 15:53
Running into the same problem with the pipeline provided in the tutorial using a local CodeReadyContainers cluster.

`Name:         petclinic-deploy-pipeline
Namespace:    pipelines-tutorial
Labels:       <none>
Annotations:  <none>
API Version:  tekton.dev/v1alpha1
Kind:         Pipeline
Metadata:
  Creation Timestamp:  2019-09-30T14:35:05Z
  Generation:          1
  Resource Version:    235517
  Self Link:           /apis/tekton.dev/v1alpha1/namespaces/pipelines-tutorial/pipelines/petclinic-deploy-pipeline
  UID:                 7eb56f64-e38f-11e9-833d-52fdfc072182
Spec:
  Resources:
    Name:  app-git
    Type:  git
    Name:  app-image
    Type:  image
  Tasks:
    Name:  build
    Params:
      Name:   TLSVERIFY
      Value:  false
    Resources:
      Inputs:
        Name:      source
        Resource:  app-git
      Outputs:
        Name:      image
        Resource:  app-image
    Task Ref:
      Name:  s2i-java-8
    Name:    deploy
    Params:
      Name:   ARGS
      Value:  rollout latest spring-petclinic
    Run After:
      build
    Task Ref:
      Name:  openshift-client
Events:      <none>
`
I Found that the path for the upload folder is actually /gen-source/upload and upload/src is going to /workspace, looking for a way to actually solve this and put the correct path 
![image](https://user-images.githubusercontent.com/54948088/65908242-69be6700-e39c-11e9-9a2a-dfa1bbe0aab5.png)

**Comment by raffamendes** [comment] 2019-10-01 12:23
I got the problem to stop showing changing the workingdir on the s2i-java-8 task, but now the app is not being built by maven, so the deploy fails, still working on this and try to make it work.

Change made:
`workingDir: /workspace/source`
to
`  workingDir: /gen-source/source`

**Comment by raffamendes** [comment] 2019-10-01 13:20
Don't really know what happened, but I restarted the crc cluster, cleaned the PVC's and changed back the workingdir do workspace/source and it worked.

**Comment by siamaksade** [comment] 2019-10-22 16:44
@raffamendes  I close this issue for now. Re-open if it appears again

**Closed as completed by siamaksade** 2019-10-22 16:45 UTC

**Comment by kamleshjec** [comment] 2020-05-11 18:56
I am using OCP 4.2 and tekton version: v0.11.0
[build : build] --> fa56c9853f8
[build : build] STEP 3: USER root
[build : build] --> 4a7e70bb2e8
[build : build] STEP 4: COPY upload/src /tmp/src
[build : build] error building at STEP "COPY upload/src /tmp/src": no files found matching "/workspace/upload/src": no such file or directory
any lead will be appreciated..  Thanks
failed to get logs for task build : container step-build has failed  : Error : [{"name":"","digest":"","key":"StartedAt","value":"2020-05-11T18:51:40Z","resourceRef":{}}]
